# hypr/hyprlock.conf

background {
  monitor=HDMI-A-1
  blur_passes=2
  blur_size=4
  brightness=0.3
  color=rgba(22, 22, 22, 1.0)
  contrast=0.69
  noise=0
  path=$HOME/.wallpaper/lock/vert.png
  vibrancy=0
  vibrancy_darkness=0
}

background {
  monitor=DP-1
  path=$HOME/.wallpaper/lock/horiz.png
}

label {
  monitor=DP-1
  color=rgb(22, 22, 22)
  font_family=JetBrains Mono Nerd Font Mono ExtraBold
  font_size=175
  halign=center
  position=0, 300
  text=$TIME
  valign=center
}

background {
  monitor=DP-1
  zindex = 1
  keep_aspect_ratio = true
  rounding = 0
  border_size = 0
  path=$HOME/.wallpaper/lock/overlay.png
}

image {
  monitor=DP-1
  halign=center
  path=$HOME/.face.icon
  position=0, 0
  valign=center
}

input-field {
  monitor=DP-1
  size=200, 50
  bothlock_color=-1
  capslock_color=-1
  check_color=rgb(142, 214, 113)
  dots_center=true
  dots_rounding=-1
  dots_size=0.33
  dots_spacing=0.15
  fade_on_empty=true
  fade_timeout=1000
  fail_color=rgb(214, 113, 123)
  font_color=rgb(188, 188, 188)
  halign=center
  hide_input=false
  inner_color=rgb(22, 22, 22)
  invert_numlock=false
  numlock_color=-1
  outer_color=rgb(36, 36, 36)
  outline_thickness=3
  placeholder_text=<i>Input Password...</i>
  position=0, -150
  rounding=-1
  swap_font_color=false
  valign=center
}

label {
  monitor=DP-1
  color=rgb(22, 22, 22)
  font_family=JetBrains Mono Nerd Font Mono Bold
  font_size=22
  halign=center
  position=0, 150
  text=cmd[update:1000] echo $(date +"%A, %B %d")
  valign=center
}

